# Generated by Django 3.1 on 2021-09-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100, null=True, verbose_name='model')),
                ('color', models.CharField(max_length=100, null=True, verbose_name='color')),
                ('date', models.DateField()),
            ],
        ),
    ]
